### ISSUE TITLE
Blocks are not broken but still get items back

### ISSUE THREAD

**Issue by thinh2118** [RKAbdul/OreSpawners#5] opened 2020-09-17 23:41 UTC
Blocks are not broken but still get items back

**Comment by thinh2118** [comment] 2020-09-17 23:42
This error appears only occasionally, when you're done using r close the server and rejoin the server.

**Comment by RKAbdul** [comment] 2020-09-18 06:09
Hey, can you explain a bit more with details.
Please point out the following and we may help you out
- What actually happens?
- What do except?
- Any errors?
- How to recreate the problem?

**Comment by thinh2118** [comment] 2020-09-18 11:25
The block is not broken yet but has received the item back

**Comment by AGTHARN** [comment] 2020-09-18 11:52
Hi, we can't seem to reproduce this. We have tested and rechecked the code and we can't seem to find anything linked to your problem. Hence, this might be caused by another plugin. If possible, please provide a video and reopen the issue. For now, I will tag this as an invalid issue. Thank you for using the plugin!

**Comment by RKAbdul** [comment] 2020-09-19 04:10
I got the bug in my own server now, so i understand it. I will reopen the ticket and get to fix it

**Comment by RKAbdul** [comment] 2020-09-19 12:39
This issue has been fixed in the latest release  0.3.2

**Closed as completed by RKAbdul** 2020-09-19 12:39 UTC
Labels: Fixed
